In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
url = "https://raw.githubusercontent.com/dineshpiyasamara/LaptopPricePredictor/master/model%20building/laptop_price.csv"

In [3]:
data = pd.read_csv(url, encoding='latin-1')

In [4]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94

In [5]:
data.shape

(1303, 12)

In [6]:
data.isnull()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,False,False,False,False,False,False,False,False,False,False,False,False
1299,False,False,False,False,False,False,False,False,False,False,False,False
1300,False,False,False,False,False,False,False,False,False,False,False,False
1301,False,False,False,False,False,False,False,False,False,False,False,False
1302,False,False,False,False,False,False,False,False,False,False,False,False

In [7]:
data.isnull().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   object
 8   Gpu               1303 non-null   object
 9   OpSys             1303 non-null   object
 10  Weight            1303 non-null   object
 11  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 122.3+ KB

In [9]:
data = data.drop(columns=['laptop_ID'])

In [10]:
data.head(2)

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94

               Inches  Price_euros
Inches       1.000000     0.068197
Price_euros  0.068197     1.000000

In [12]:
data['Ram'] = data['Ram'].str.replace('GB', '').astype('int32')

In [14]:
data['Weight'] = data['Weight'].str.replace('kg','').astype('float64')

In [15]:
data.head(2)

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94

In [16]:
data = data.drop(columns=['Inches'])

In [17]:
data.corr(numeric_only=True)['Price_euros']

Ram            0.743007
Weight         0.210370
Price_euros    1.000000
Name: Price_euros, dtype: float64

In [18]:
data.head(2)

,Company,Product,TypeName,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,Apple,MacBook Pro,Ultrabook,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69
1,Apple,Macbook Air,Ultrabook,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94

In [19]:
data['Company'].value_counts()

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Mediacom       7
Razer          7
Microsoft      6
Vero           4
Xiaomi         4
Chuwi          3
Fujitsu        3
Google         3
LG             3
Huawei         2
Name: count, dtype: int64

In [20]:
def add_company(company):
    if company=='Dell' or company=='Lenovo' or company=='HP' or company=='Asus' or company=='Acer' or company=='MSI' or company=='Toshiba' or company=='Apple' :
        return company
    else:
        return 'other'

data['Company'] =  data['Company'].apply(add_company)

In [21]:
data['Company'].value_counts()

Company
Dell       297
Lenovo     297
HP         274
Asus       158
Acer       103
MSI         54
other       51
Toshiba     48
Apple       21
Name: count, dtype: int64

In [22]:
data['Product'].value_counts()

Product
XPS 13                                 30
Inspiron 3567                          29
250 G6                                 21
Vostro 3568                            19
Legion Y520-15IKBN                     19
                                       ..
L403NA-GA013TS (N3350/4GB/32GB/W10)     1
IdeaPad 500-15ISK                       1
GP62M 7RDX                              1
V110-15ISK (i3-6006U/4GB/1TB/No         1
15-BA015wm (E2-7110/4GB/500GB/W10)      1
Name: count, Length: 618, dtype: int64

In [23]:
data = data.drop(columns=['Product'])

In [24]:
data['TypeName'].value_counts()

TypeName
Notebook              727
Gaming                205
Ultrabook             196
2 in 1 Convertible    121
Workstation            29
Netbook                25
Name: count, dtype: int64

In [25]:
data['ScreenResolution'].value_counts()

ScreenResolution
Full HD 1920x1080                                507
1366x768                                         281
IPS Panel Full HD 1920x1080                      230
IPS Panel Full HD / Touchscreen 1920x1080         53
Full HD / Touchscreen 1920x1080                   47
1600x900                                          23
Touchscreen 1366x768                              16
Quad HD+ / Touchscreen 3200x1800                  15
IPS Panel 4K Ultra HD 3840x2160                   12
IPS Panel 4K Ultra HD / Touchscreen 3840x2160     11
4K Ultra HD / Touchscreen 3840x2160               10
IPS Panel 1366x768                                 7
Touchscreen 2560x1440                              7
4K Ultra HD 3840x2160                              7
IPS Panel Retina Display 2304x1440                 6
IPS Panel Retina Display 2560x1600                 6
Touchscreen 2256x1504                              6
IPS Panel Quad HD+ / Touchscreen 3200x1800         6
IPS Panel Touchscreen 2560x1440                    5
IPS Panel Retina Display 2880x1800                 4
1440x900                                           4
IPS Panel Touchscreen 1920x1200                    4
IPS Panel 2560x1440                                4
IPS Panel Quad HD+ 2560x1440                       3
IPS Panel Touchscreen 1366x768                     3
Quad HD+ 3200x1800                                 3
1920x1080                                          3
2560x1440                                          3
Touchscreen 2400x1600                              3
IPS Panel Quad HD+ 3200x1800                       2
IPS Panel Full HD 2160x1440                        2
IPS Panel Touchscreen / 4K Ultra HD 3840x2160      2
IPS Panel Full HD 1366x768                         1
Touchscreen / Quad HD+ 3200x1800                   1
IPS Panel Retina Display 2736x1824                 1
IPS Panel Full HD 2560x1440                        1
IPS Panel Full HD 1920x1200                        1
Touchscreen / Full HD 1920x1080                    1
Touchscreen / 4K Ultra HD 3840x2160                1
IPS Panel Touchscreen 2400x1600                    1
Name: count, dtype: int64

In [27]:
data['Touchscreen'] = data['ScreenResolution'].apply(lambda x:1 if 'Touchscreen' in x else 0 )
data['IPS'] = data['ScreenResolution'].apply(lambda x:1 if 'IPS' in x else 0 )

In [30]:
data.head(2)

,Company,TypeName,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,IPS
0,Apple,Ultrabook,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1
1,Apple,Ultrabook,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94,0,0

In [29]:
data = data.drop(columns= ['ScreenResolution'])

In [31]:
data['Cpu'].value_counts()

Cpu
Intel Core i5 7200U 2.5GHz       190
Intel Core i7 7700HQ 2.8GHz      146
Intel Core i7 7500U 2.7GHz       134
Intel Core i7 8550U 1.8GHz        73
Intel Core i5 8250U 1.6GHz        72
                                ...
Intel Core i5 7200U 2.70GHz        1
Intel Core M M7-6Y75 1.2GHz        1
Intel Core M 6Y54 1.1GHz           1
AMD E-Series 9000 2.2GHz           1
Samsung Cortex A72&A53 2.0GHz      1
Name: count, Length: 118, dtype: int64

In [32]:
data['Cpu_name'] = data['Cpu'].apply(lambda x:' '.join(x.split()[0:3]))

In [33]:
data['Cpu_name'].value_counts()

Cpu_name
Intel Core i7               527
Intel Core i5               423
Intel Core i3               136
Intel Celeron Dual           80
Intel Pentium Quad           27
Intel Core M                 19
AMD A9-Series 9420           12
AMD A6-Series 9220            8
Intel Celeron Quad            8
AMD A12-Series 9720P          7
Intel Atom x5-Z8350           5
AMD A8-Series 7410            4
Intel Atom x5-Z8550           4
AMD A9-Series 9410            3
Intel Pentium Dual            3
AMD Ryzen 1700                3
AMD A9-Series A9-9420         2
AMD E-Series E2-9000e         2
AMD A10-Series A10-9620P      2
AMD A6-Series A6-9220         2
AMD E-Series 7110             2
AMD A10-Series 9620P          2
AMD A10-Series 9600P          2
Intel Xeon E3-1505M           2
Intel Xeon E3-1535M           2
Intel Atom X5-Z8350           2
Intel Atom x5-Z8300           1
AMD E-Series 6110             1
AMD E-Series 9000e            1
AMD E-Series E2-6110          1
AMD FX 9830P                  1
AMD Ryzen 1600                1
Intel Atom Z8350              1
AMD A6-Series 7310            1
AMD E-Series E2-9000          1
AMD A12-Series 9700P          1
AMD FX 8800P                  1
AMD A4-Series 7210            1
Samsung Cortex A72&A53        1
AMD E-Series 9000             1
Name: count, dtype: int64

In [34]:
def cpu_name(cpu):
    if  cpu == 'Intel Core i7' or cpu == 'Intel Core i5' or cpu == 'Intel Core i3' :
        return cpu
    else:
        if cpu.split()[0]=='AMD':
            return 'AMD'
        else :
            return 'other'

data['Cpu_name']= data['Cpu_name'].apply(cpu_name)

In [35]:
data['Cpu_name'].value_counts()

Cpu_name
Intel Core i7    527
Intel Core i5    423
other            155
Intel Core i3    136
AMD               62
Name: count, dtype: int64

In [36]:
data = data.drop(columns=['Cpu'])

In [37]:
data.head(2)

,Company,TypeName,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,IPS,Cpu_name
0,Apple,Ultrabook,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1,Intel Core i5
1,Apple,Ultrabook,8,Intel HD Graphics 6000,macOS,1.34,898.94,0,0,Intel Core i5

In [38]:
data['Gpu'].value_counts()

Gpu
Intel HD Graphics 620      281
Intel HD Graphics 520      185
Intel UHD Graphics 620      68
Nvidia GeForce GTX 1050     66
Nvidia GeForce GTX 1060     48
                          ...
Nvidia Quadro M500M          1
AMD Radeon R7 M360           1
Nvidia Quadro M3000M         1
Nvidia GeForce 960M          1
ARM Mali T860 MP4            1
Name: count, Length: 110, dtype: int64

In [39]:
data['gpu_name'] = data['Gpu'].apply(lambda x: ' ' .join(x.split()[0:1]))

In [40]:
data['gpu_name'].value_counts()

gpu_name
Intel     722
Nvidia    400
AMD       180
ARM         1
Name: count, dtype: int64

In [42]:
data = data[data['gpu_name'] != 'ARM']

In [43]:
data.shape

(1302, 11)

In [44]:
data.head(2)

,Company,TypeName,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,IPS,Cpu_name,gpu_name
0,Apple,Ultrabook,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1,Intel Core i5,Intel
1,Apple,Ultrabook,8,Intel HD Graphics 6000,macOS,1.34,898.94,0,0,Intel Core i5,Intel

In [45]:
data = data.drop(columns=['Gpu'])

In [46]:
data['OpSys'].value_counts()

OpSys
Windows 10      1072
No OS             66
Linux             62
Windows 7         45
Chrome OS         26
macOS             13
Mac OS X           8
Windows 10 S       8
Android            2
Name: count, dtype: int64

In [47]:
def add_os(os):
    if os== 'Windows 10' or  os== 'Windows 7' or os== 'Windows 10 S'  :
        return 'Windows'
    elif os=='macOS' or os=='Mac OS X':
        return 'mac'
    elif os=='Linux' :
        return os
    else :
        return 'other'
        
data['OpSys'] = data['OpSys'].apply(add_os)

In [48]:
data['OpSys'].value_counts()

OpSys
Windows    1125
other        94
Linux        62
mac          21
Name: count, dtype: int64

In [49]:
data.head(2)

,Company,TypeName,Ram,OpSys,Weight,Price_euros,Touchscreen,IPS,Cpu_name,gpu_name
0,Apple,Ultrabook,8,mac,1.37,1339.69,0,1,Intel Core i5,Intel
1,Apple,Ultrabook,8,mac,1.34,898.94,0,0,Intel Core i5,Intel

In [50]:
data = pd.get_dummies(data)

In [51]:
data.head(2)

,Ram,Weight,Price_euros,Touchscreen,IPS,Company_Acer,Company_Apple,Company_Asus,Company_Dell,Company_HP,...,OpSys_mac,OpSys_other,Cpu_name_AMD,Cpu_name_Intel Core i3,Cpu_name_Intel Core i5,Cpu_name_Intel Core i7,Cpu_name_other,gpu_name_AMD,gpu_name_Intel,gpu_name_Nvidia
0,8,1.37,1339.69,0,1,False,True,False,False,False,...,True,False,False,False,True,False,False,False,True,False
1,8,1.34,898.94,0,0,False,True,False,False,False,...,True,False,False,False,True,False,False,False,True,False

In [53]:

x= data.drop(columns=['Price_euros'])
y = data['Price_euros']

In [54]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test = train_test_split(x,y, test_size=0.25)

In [56]:
def model_acc(model):
    model.fit(x_train, y_train)
    acc = model.score(x_test,y_test)
    print(str(model)+  '->'+ str(acc))

In [57]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
model_acc(lr)

from sklearn.linear_model import Lasso
ls= Lasso()
model_acc(ls)

from sklearn.tree import DecisionTreeRegressor
dt= DecisionTreeRegressor()
model_acc(dt)

from sklearn.ensemble import RandomForestRegressor
rf= RandomForestRegressor()
model_acc(rf)

LinearRegression()->0.7019813688485443
Lasso()->0.7006781844393764
DecisionTreeRegressor()->0.7750059495133721
RandomForestRegressor()->0.8159507857739143

In [60]:
from sklearn.model_selection import GridSearchCV
parameters = {'n_estimators':[10,50,100],
              'criterion':['squarred_error', 'absolute_error', 'poisson']}

grid_obj = GridSearchCV(estimator = rf, param_grid= parameters)
grid_fit = grid_obj.fit(x_train,y_train)
best_model = grid_fit.best_estimator_
best_model

C:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
15 fits failed out of a total of 45.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'squarred_error' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan 0.74216272 0.76606238 0.76382602
 0.74817615 0.75633319 0.75307666]
  warnings.warn(

RandomForestRegressor(criterion='absolute_error', n_estimators=50)

In [61]:
best_model.score(x_test,y_test)

0.8123738547168682

In [62]:
import pickle
with open('predictor.pickle', 'wb') as file:
    pickle.dump(best_model, file)

In [63]:
x_train.columns

Index(['Ram', 'Weight', 'Touchscreen', 'IPS', 'Company_Acer', 'Company_Apple',
       'Company_Asus', 'Company_Dell', 'Company_HP', 'Company_Lenovo',
       'Company_MSI', 'Company_Toshiba', 'Company_other',
       'TypeName_2 in 1 Convertible', 'TypeName_Gaming', 'TypeName_Netbook',
       'TypeName_Notebook', 'TypeName_Ultrabook', 'TypeName_Workstation',
       'OpSys_Linux', 'OpSys_Windows', 'OpSys_mac', 'OpSys_other',
       'Cpu_name_AMD', 'Cpu_name_Intel Core i3', 'Cpu_name_Intel Core i5',
       'Cpu_name_Intel Core i7', 'Cpu_name_other', 'gpu_name_AMD',
       'gpu_name_Intel', 'gpu_name_Nvidia'],
      dtype='object')

In [ ]:
best_model.predict([[]]) #predicting